DROP TABLE IF EXISTS FORMATEURS CASCADE;
DROP TABLE IF EXISTS FORMATIONS CASCADE;
DROP TABLE IF EXISTS SEANCES CASCADE;

DROP TABLE IF EXISTS BATCH_JOB_EXECUTION CASCADE;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION_CONTEXT CASCADE;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION_PARAMS CASCADE;
DROP TABLE IF EXISTS BATCH_JOB_INSTANCE CASCADE;
DROP TABLE IF EXISTS BATCH_STEP_EXECUTION CASCADE;
DROP TABLE IF EXISTS BATCH_STEP_EXECUTION_CONTEXT CASCADE;

DROP SEQUENCE IF EXISTS BATCH_JOB_SEQ CASCADE;
DROP SEQUENCE IF EXISTS BATCH_JOB_EXECUTION_SEQ CASCADE;
DROP SEQUENCE IF EXISTS BATCH_STEP_EXECUTION_SEQ CASCADE;

CREATE TABLE FORMATEURS(
	id INT NOT NULL PRIMARY KEY,
	nom VARCHAR(12) NOT NULL,
	prenom VARCHAR(12) NOT NULL,
	"adresse-email" VARCHAR(50) NOT NULL
);

CREATE TABLE FORMATIONS(
	CODE VARCHAR(20) NOT NULL PRIMARY KEY,
	libelle VARCHAR(200) NOT NULL,
	descriptif VARCHAR(500) NOT NULL
);

CREATE TABLE SEANCES(
	code_formation VARCHAR(20) NOT NULL,
	id_formateur INT NOT NULL,
	date_debut DATE NOT NULL,
	date_fin DATE NOT NULL,
	CONSTRAINT FK_FORMATEURS FOREIGN KEY(id_formateur) REFERENCES FORMATEURS(id),
	CONSTRAINT FK_FORMATIONS FOREIGN KEY(code_formation) REFERENCES FORMATIONS(CODE)
);
